# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18d631584e80478a12f9f4a9f1c54134de713fd564b2a54353455bde295a692da50ee19665c72bb8001e6aa53bb49babe1c00e07d18d0b6fefe0065477f185a4

test:
  secret_key_base: 15df71cdaeefd12235f978bc6022a532a801d9b27b77a3013cf420ad6f6ce21a1c9f50e1d369b5c7e229879c591f30f1ea7c659d081e3887a6bb1b144724298b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
